export const START_GET_CATEGORIES = "START_GET_CATEGORIES";
export const COMPLETE_GET_CATEGORIES = "COMPLETE_GET_CATEGORIES";
export const ERROR_GET_CATEGORIES = "ERROR_GET_CATEGORIES";

export const START_CREATE_CATEGORY = "START_CREATE_CATEGORY";
export const COMPLETE_CREATE_CATEGORY = "COMPLETE_CREATE_CATEGORY";
export const ERROR_CREATE_CATEGORY = "ERROR_CREATE_CATEGORY";

export const START_UPDATE_CATEGORY = "START_UPDATE_CATEGORY";
export const COMPLETE_UPDATE_CATEGORY = "COMPLETE_UPDATE_CATEGORY";
export const ERROR_UPDATE_CATEGORY = "ERROR_UPDATE_CATEGORY";

export const START_DELETE_CATEGORY = "START_DELETE_CATEGORY";
export const COMPLETE_DELETE_CATEGORY = "COMPLETE_DELETE_CATEGORY";
export const ERROR_DELETE_CATEGORY = "ERROR_DELETE_CATEGORY";