export const START_LOGIN = "START_LOGIN";
export const COMPLETE_LOGIN = "COMPLETE_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";

export const START_REGISTER = "START_REGISTER";
export const COMPLETE_REGISTER = "COMPLETE_REGISTER";
export const ERROR_REGISTER = "ERROR_REGISTER";

export const START_LOGOUT = "START_LOGOUT";
export const COMPLETE_LOGOUT = "COMPLETE_LOGOUT";
export const ERROR_LOGOUT = "ERROR_LOGOUT";

export const START_GET_CATEGORIES = "START_GET_CATEGORIES";
export const COMPLETE_GET_CATEGORIES = "COMPLETE_GET_CATEGORIES";
export const ERROR_GET_CATEGORIES = "ERROR_GET_CATEGORIES";