export const START_GET_MATERIALS = "START_GET_MATERIALS";
export const COMPLETE_GET_MATERIALS = "COMPLETE_GET_MATERIALS";
export const ERROR_GET_MATERIALS = "ERROR_GET_MATERIALS";

export const START_CREATE_MATERIAL = "START_CREATE_MATERIAL";
export const COMPLETE_CREATE_MATERIAL = "COMPLETE_CREATE_MATERIAL";
export const ERROR_CREATE_MATERIAL = "ERROR_CREATE_MATERIAL";

export const START_UPDATE_MATERIAL = "START_UPDATE_MATERIAL";
export const COMPLETE_UPDATE_MATERIAL = "COMPLETE_UPDATE_MATERIAL";
export const ERROR_UPDATE_MATERIAL = "ERROR_UPDATE_MATERIAL";

export const START_DELETE_MATERIAL = "START_DELETE_MATERIAL";
export const COMPLETE_DELETE_MATERIAL = "COMPLETE_DELETE_MATERIAL";
export const ERROR_DELETE_MATERIAL = "ERROR_DELETE_MATERIAL";