export const START_GET_MEASURES = "START_GET_MEASURES";
export const COMPLETE_GET_MEASURES = "COMPLETE_GET_MEASURES";
export const ERROR_GET_MEASURES = "ERROR_GET_MEASURES";

export const START_CREATE_MEASURE = "START_CREATE_MEASURE";
export const COMPLETE_CREATE_MEASURE = "COMPLETE_CREATE_MEASURE";
export const ERROR_CREATE_MEASURE = "ERROR_CREATE_MEASURE";

export const START_UPDATE_MEASURE = "START_UPDATE_MEASURE";
export const COMPLETE_UPDATE_MEASURE = "COMPLETE_UPDATE_MEASURE";
export const ERROR_UPDATE_MEASURE = "ERROR_UPDATE_MEASURE";

export const START_DELETE_MEASURE = "START_DELETE_MEASURE";
export const COMPLETE_DELETE_MEASURE = "COMPLETE_DELETE_MEASURE";
export const ERROR_DELETE_MEASURE = "ERROR_DELETE_MEASURE";